name: Workflow

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "playwright-ts-web-api"
        required: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install browsers
        run: npx playwright install

      - name: Set TS_NODE_PROJECT variable
        run: export TS_NODE_PROJECT=./tsconfig.json

      - name: Run Playwright tests
        run: npm run test:web

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30